### ISSUE TITLE
compatibility with cake 3.5.

### ISSUE THREAD

**Issue by cewi** [chinpei215/cakephp-intlless#1]
Hi,

Cake\I18n\I18n::translator() ist now deprecated and invoking __d() throws an error under Cake 3.5. Changing the function name in Intlless\I18n to getTranslator() solved the problem for me, but maybe there are other things to change, to get full 3.5. compatibility.

BTW: Thank you for the plugin. Helped me a lot!

**Comment by chinpei215** [comment]
@cewi Sorry for my late reply and thank you for reporting this issue. I haven't test this plugin in 3.5 yet. Let me check what happens.

**Comment by chinpei215** [comment]
Fixed in 1.0.2. Thank you.
